FROM python:2.7.14-slim-jessie 
MAINTAINER Rakshith "hehaichi@gmail.com"
WORKDIR /app
ADD . /app
ADD dependencies.txt /dependencies.txt
RUN pip install -r /dependencies.txt
EXPOSE 8000
ENTRYPOINT ["python"]
CMD ["manage.py", "runserver"]
